-- SQL queries to define the database schema


CREATE TABLE Users (
       user_id INT GENERATED BY DEFAULT AS IDENTITY,
       PRIMARY KEY (user_id),
       first_name VARCHAR(50) NOT NULL,
       last_name VARCHAR(50) NOT NULL,
       email VARCHAR(50) NOT NULL,
       UNIQUE (email),
       password_hash TEXT NOT NULL,
       phone_number VARCHAR(50),
       user_role enum_user_role NOT NULL,
       created_at TIMESTAMP(3) DEFAULT now()
);

CREATE TABLE Property (
       property_id INT GENERATED BY DEFAULT AS IDENTITY,
       PRIMARY KEY (property_id),
       host_id INT,
       FOREIGN KEY (host_id) REFERENCES Users(user_id),
       property_name VARCHAR(50) NOT NULL,
       description VARCHAR(255) NOT NULL,
       location VARCHAR(50) NOT NULL,
       pricepernight DECIMAL(10, 3) NOT NULL,
       created_at TIMESTAMP(3) DEFAULT now(),
       updated_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Booking (
       booking_id INT GENERATED BY DEFAULT AS IDENTITY,
       PRIMARY KEY (booking_id),
       property_id INT,
       FOREIGN KEY (property_id) REFERENCES Property(property_id),
       user_id INT,
       FOREIGN KEY (user_id) REFERENCES Users(user_id),
       start_date DATE NOT NULL,
       end_date DATE NOT NULL,
       total_price DECIMAL(10, 3) NOT NULL,
       status enum_status NOT NULL,
       created_at TIMESTAMP(3) DEFAULT now()
);

CREATE TABLE Payment (
       payment_id INT GENERATED BY DEFAULT AS IDENTITY,
       PRIMARY KEY (payment_id),
       booking_id INT,
       FOREIGN KEY (booking_id) REFERENCES Booking(booking_id),
       amount DECIMAL(10, 3) NOT NULL,
       payment_date TIMESTAMP(3) DEFAULT now(),
       payment_method enum_payment_method NOT NULL
);

CREATE TABLE Review (
       review_id INT GENERATED BY DEFAULT AS IDENTITY,
       PRIMARY KEY (review_id),
       property_id INT,
       FOREIGN KEY (property_id) REFERENCES Property(property_id),
       user_id INT,
       FOREIGN KEY (user_id) REFERENCES Users(user_id),
       rating INTEGER NOT NULL,
       CHECK (rating >= 1 AND rating <= 5),
       comment VARCHAR(255),
       created_at TIMESTAMP(3) DEFAULT now()
);

CREATE TABLE Message (
       message_id INT GENERATED BY DEFAULT AS IDENTITY,
       PRIMARY KEY (message_id),
       sender_id INT,
       FOREIGN KEY (sender_id) REFERENCES Users(user_id),
       recipient_id INT,
       FOREIGN KEY (recipient_id) REFERENCES Users(user_id),
       message_body VARCHAR(255) NOT NULL,
       sent_at TIMESTAMP(3) DEFAULT now()
);

-- Indexing on the User, Property, Booking and Payment tables

CREATE INDEX idx_email
ON Users (email);

CREATE INDEX idx_property_id
ON Property (property_id);

CREATE INDEX idx_property_id
ON Booking (property_id);

CREATE INDEX idx_booking_id
ON Booking (booking_id);

CREATE INDEX idx_booking_id
ON Payment (booking_id);

-- Create a function and a trigger enabling auto-update of 'timestamp' attribute
-- The FUNCTION
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = CURRENT_TIMESTAMP;
	RETURN NEW;
END
$$ LANGUAGE plpgsql;

-- The TRIGGER
CREATE TRIGGER set_updated_at
BEFORE UPDATE ON Property
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
